books/urls.py
from django.urls import path

from books.views import BookListView

urlpatterns = [
    path('books/', BookListView.as_view(), name='books'),
]

hollymovies_5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from movies.views import RegistrationView, ProfileCreateView, ProfileUpdateView

urlpatterns = [
    path('accounts/profile/create/', ProfileCreateView.as_view(), name='create_profile'),
    path('accounts/profile/update/<int:pk>/', ProfileUpdateView.as_view(), name='update_profile'),
    path('accounts/register/', RegistrationView.as_view(), name='register'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('', include('movies.urls'), name='movies'),
    path('books/', include('books.urls'), name='books'),
]

movies/urls.py
from django.urls import path
from movies.views import HomepageView, ActorListView, MovieListView, MovieDetailView, \
    ActorDetailView, Jinja2TestingView, DirectorListView, DirectorDetailView, ContactView, CreateMovieView, \
    CreateActorView, UpdateMovieView, UpdateActorView, DeleteMovieView, DeleteActorView, CreateDirectorView, \
    UpdateDirectorView, DeleteDirectorView

urlpatterns = (
    path('', HomepageView.as_view(), name='homepage'),
    path('actors/', ActorListView.as_view(), name='actors'),
    path('movies/', MovieListView.as_view(), name='movies'),
    path('movie/<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('actor/<int:pk>/', ActorDetailView.as_view(), name='actor_detail'),
    path('directors/', DirectorListView.as_view(), name='directors'),
    path('director/<int:pk>/', DirectorDetailView.as_view(), name='director_detail'),
    path('testing/', Jinja2TestingView.as_view(), name='jinja2_testing_view'),
    path('contact/', ContactView.as_view(), name='contact_view'),
    path('movie/create/', CreateMovieView.as_view(), name='create_movie'),
    path('actor/create/', CreateActorView.as_view(), name='create_actor'),
    path('movie/update/<int:pk>/', UpdateMovieView.as_view(), name='update_movie'),
    path('actor/update/<int:pk>/', UpdateActorView.as_view(), name='update_actor'),
    path('movie/delete/<int:pk>/', DeleteMovieView.as_view(), name='delete_movie'),
    path('actor/delete/<int:pk>/', DeleteActorView.as_view(), name='delete_actor'),
    path('director/create/', CreateDirectorView.as_view(), name='create_director'),
    path('director/update/<int:pk>/', UpdateDirectorView.as_view(), name='update_director'),
    path('director/delete/<int:pk>/', DeleteDirectorView.as_view(), name='delete_director'),
)

movies/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.shortcuts import resolve_url


class BasePersonModel(models.Model):
    GENDER_MALE = 'male'
    GENDER_FEMALE = 'female'

    GENDER_CHOICES = (
        (GENDER_MALE, 'male'),
        (GENDER_FEMALE, 'female')
    )

    name = models.CharField(max_length=256)
    age = models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=100)
    born_at = models.DateField()

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Actor(BasePersonModel):
    def get_absolute_url(self):
        return resolve_url('actor_detail', pk=self.pk)


class Director(BasePersonModel):
    def get_absolute_url(self):
        return resolve_url('director_detail', pk=self.pk)


class Movie(models.Model):
    LANGUAGE_ENG = 'eng'
    LANGUAGE_CZ = 'cz'

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENG, 'english'),
        (LANGUAGE_CZ, 'czech'),
    )

    name = models.CharField(max_length=256)
    description = models.TextField()
    rating = models.IntegerField(validators=[
        MinValueValidator(0), MaxValueValidator(100)
    ])
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=5)
    released = models.DateField()
    actors = models.ManyToManyField('Actor', related_name='movies')
    director = models.ForeignKey(
        'Director',
        on_delete=models.SET_NULL,
        related_name='movies',
        null=True, blank=True,
    )
    likes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.name} : {self.id}'

    def get_absolute_url(self):
        return resolve_url('movie_detail', pk=self.id)

    class Meta:
        permissions = (
            ('can_change_director', 'Can Change director'),
        )


class Contact(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField()
    subject = models.TextField()
    phone_number = models.IntegerField()
    contact_at = models.DateField()


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile')
    address = models.CharField(max_length=256, null=True, blank=True)
    language = models.CharField(max_length=15, null=True, blank=True)
    favorite_movie = models.ForeignKey(
        Movie,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='profiles'
    )

movies/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta

from movies.models import Movie, Actor, Director, Profile


class DatePickerDateInput(forms.DateInput):
    def __init__(self, *args, **kwargs):
        kwargs.update({'attrs': {'type': 'date'}})
        super(DatePickerDateInput, self).__init__(*args, **kwargs)


class DateFieldSevenDaysFromNow(forms.DateField):
    widget = DatePickerDateInput

    def validate(self, value):
        super(DateFieldSevenDaysFromNow, self).validate(value)
        if value < timezone.now().date() + timedelta(days=7):
            raise ValidationError('Cannot create contact at earlier that 7 days from now')


def contact_name_is_not_david(value):
    if 'david' in value.lower():
        raise ValidationError('David cannot create contact')


class ContactForm(forms.Form):
    name = forms.CharField(validators=[contact_name_is_not_david, ])
    email = forms.EmailField()
    subject = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    phone_number = forms.IntegerField()
    age = forms.IntegerField(min_value=1, max_value=99)
    contact_at = DateFieldSevenDaysFromNow()
    subscribe = forms.BooleanField()

    def clean_name(self):
        return self.data.get('name').lower()


class MovieForm(forms.ModelForm):
    released = forms.DateField(widget=DatePickerDateInput())

    class Meta:
        model = Movie
        fields = '__all__'
        exclude = ['likes', ]


class ActorForm(forms.ModelForm):
    born_at = forms.DateField(widget=DatePickerDateInput())
    movies = forms.ModelMultipleChoiceField(queryset=Movie.objects.all(), required=False)

    class Meta:
        model = Actor
        fields = '__all__'

    def save(self, commit=True):
        actor = super(ActorForm, self).save(commit=commit)
        actor.movies.add(*self.cleaned_data.get('movies'))
        return actor


class DirectorForm(forms.ModelForm):
    born_at = forms.DateField(widget=DatePickerDateInput())

    class Meta:
        model = Director
        fields = '__all__'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user', )

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(ProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.request.user
        return super(ProfileForm, self).save(commit=commit)


class SearchForm(forms.Form):
    query = forms.CharField()

movies/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from movies.forms import ContactForm, MovieForm, ActorForm, DirectorForm, ProfileForm, SearchForm
from movies.models import Movie, Actor, Director, Contact, Profile
from django.views import View


class HomepageView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'number_of_movies': Movie.objects.all().count(),
            'number_of_actors': Actor.objects.all().count(),
            'number_of_directors': Director.objects.all().count(),
            'page_name': 'Homepage'
        }
        return TemplateResponse(request, 'homepage.html', context=context)


# def homepage_view(request):
#     if request.method == 'GET':
#         context = {
#             'number_of_movies': Movie.objects.all().count(),
#             'number_of_actors': Actor.objects.all().count(),
#             'page_name': 'Homepage'
#         }
#         return TemplateResponse(request, 'homepage.html', context=context)
#     elif request.method == 'POST':
#         return HttpResponse(request, 'method not allowed')


class ActorListView(LoginRequiredMixin, ListView):
    model = Actor
    template_name = 'actors.html'
    extra_context = {'page_name': 'Actors'}


class HollyMoviesDetailView(LoginRequiredMixin, DetailView):
    def get_context_data(self, **kwargs):
        context = super(HollyMoviesDetailView, self).get_context_data(**kwargs)
        context.update({'page_name': self.object.name})
        return context


class ActorDetailView(HollyMoviesDetailView):
    model = Actor
    template_name = 'actor_detail.html'

# def actors_view(request):
#     actors = Actor.objects.all()
#     context = {
#         'all_actors': actors,
#         'page_name': 'Actors',
#     }
#     return TemplateResponse(request, 'actors.html', context=context)


class DirectorListView(LoginRequiredMixin, ListView):
    model = Director
    template_name = 'directors.html'
    extra_context = {'page_name': 'Directors'}


class DirectorDetailView(HollyMoviesDetailView):
    model = Director
    template_name = 'actor_detail.html'


class MovieListView(LoginRequiredMixin, ListView):
    queryset = Movie.objects.all().order_by('-rating')
    template_name = 'movies.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MovieListView, self).get_context_data(*args, **kwargs)

        search_query = self.request.GET.get('query')
        if search_query:
            form = SearchForm(initial={'query': search_query})
            best_movies = Movie.objects.filter(rating__gte=80, name__icontains=search_query).order_by('-rating')
            worst_movies = Movie.objects.filter(rating__lte=20, name__icontains=search_query).order_by('rating')
            context['object_list'] = context['object_list'].filter(name__icontains=search_query)
        else:
            form = SearchForm()
            best_movies = Movie.objects.filter(rating__gte=80).order_by('-rating')
            worst_movies = Movie.objects.filter(rating__lte=20).order_by('rating')

        context.update({
            'best_movies': best_movies,
            'worst_movies': worst_movies,
            'page_name': 'Movies',
            'search_form': form,
        })
        return context


class MovieDetailView(UserPassesTestMixin, HollyMoviesDetailView):
    model = Movie
    template_name = 'movie_detail.html'

    def post(self, request, pk, *args, **kwargs):
        movie = self.get_object()
        movie.likes += 1
        movie.save(update_fields=['likes', ])
        return redirect('movie_detail', pk=pk)

    def test_func(self):
        if self.request.user.username == 'honza':
            return False
        return True


# def movies_view(request):
#     all_movies = Movie.objects.all().order_by('-rating')  # SELECT * FROM movies_movie;
#     best_movies = Movie.objects.filter(rating__gte=80).order_by('-rating')  # SELECT * FROM movies_movie WHERE rating GTE 80;
#     worst_movies = Movie.objects.filter(rating__lte=20).order_by('rating')
#     context = {
#         'all_movies': all_movies,
#         'best_movies': best_movies,
#         'worst_movies': worst_movies,
#         'page_name': 'Movies',
#     }
#     return TemplateResponse(request, 'movies.html', context=context)


class Jinja2TestingView(LoginRequiredMixin, TemplateView):
    template_name = 'jinja2_testing.html'
    extra_context = {
        'testing_list': ['index_1', 'index_2', 'index_3'],
        'testing_dict': {'key_1': 'value_1', 'key_2': 'value_2'},
        'testing_queryset': Movie.objects.all(),
    }

# def jinja2_testing_view(request):
#     index_list = ['index_1', 'index_2', 'index_3']
#     index_1 = index_list[0]
#
#     testing_dict = {'key_1': 'value_1', 'key_2': 'value_2'}
#     value_1 = testing_dict['key_1']
#
#     context = {
#             'testing_list': index_list,
#             'testing_dict': testing_dict,
#             'testing_queryset': Movie.objects.all(),
#     }
#     return TemplateResponse(request, 'jinja2_testing.html', context=context)


# class ContactView(View):
#     def get(self, request, *args, **kwargs):
#         context = {
#             'form': ContactForm()
#         }
#         return TemplateResponse(request, 'contact.html', context=context)
#
#     def post(self, request, *args, **kwargs):
#         bounded_form = ContactForm(request.POST)
#         if not bounded_form.is_valid():
#             return TemplateResponse(request, 'contact.html', context={'form': bounded_form})
#
#         name = bounded_form.cleaned_data.get('name')
#         phone_number = bounded_form.cleaned_data.get('phone_number')
#         email = bounded_form.cleaned_data.get('email')
#         subject = bounded_form.cleaned_data.get('subject')
#         contact_at = bounded_form.cleaned_data.get('contact_at')
#
#         Contact.objects.create(
#             name=name,
#             phone_number=phone_number,
#             email=email,
#             subject=subject,
#             contact_at=contact_at
#         )
#
#         return TemplateResponse(request, 'contact.html', context={'form': ContactForm()})

class ContactView(LoginRequiredMixin, FormView):
    template_name = 'contact.html'
    form_class = ContactForm

    def form_valid(self, form):
        name = form.cleaned_data.get('name')
        phone_number = form.cleaned_data.get('phone_number')
        email = form.cleaned_data.get('email')
        subject = form.cleaned_data.get('subject')
        contact_at = form.cleaned_data.get('contact_at')

        Contact.objects.create(
            name=name,
            phone_number=phone_number,
            email=email,
            subject=subject,
            contact_at=contact_at
        )
        return TemplateResponse(self.request, 'contact.html', context={'form': ContactForm()})

    def form_invalid(self, form):
        return TemplateResponse(self.request, 'contact.html', context={'form': form})


class CreateMovieView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = 'movie_create.html'
    form_class = MovieForm
    model = Movie
    permission_required = 'movies.add_movie'


class CreateActorView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = 'actor_create.html'
    form_class = ActorForm
    model = Actor
    permission_required = 'movies.add_actor'


class UpdateMovieView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'movie_update.html'
    form_class = MovieForm
    model = Movie
    permission_required = 'movies.change_movie'


class UpdateActorView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'actor_update.html'
    form_class = ActorForm
    model = Actor
    permission_required = 'movies.change_actor'


class DeleteMovieView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('movies')
    permission_required = 'movies.delete_movie'


class DeleteActorView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'actor_confirm_delete.html'
    model = Actor
    success_url = reverse_lazy('actors')
    permission_required = 'movies.delete_actor'


class CreateDirectorView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = 'director_create.html'
    form_class = DirectorForm
    model = Director
    permission_required = 'movies.add_director'


class UpdateDirectorView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'director_update.html'
    form_class = DirectorForm
    model = Director
    permission_required = 'movies.change_director'


class DeleteDirectorView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'director_confirm_delete.html'
    model = Director
    success_url = reverse_lazy('directors')
    permission_required = 'movies.delete_director'


class RegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')


class ProfileCreateView(LoginRequiredMixin, CreateView):
    form_class = ProfileForm
    template_name = 'registration/profile_create.html'
    success_url = reverse_lazy('homepage')

    def get_form_kwargs(self):
        kwargs = super(ProfileCreateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class ProfileUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):

movies/templates/actor_confirm_delete.html
{% extends "base.html" %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete actor "{{ object.name }}" from database?
    </p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

movies/templates/actor_detail.html
{% include "base.html" %}


{% block body %}
    Name: {{ object.name }}<br>
    Age: {{ object.age }}<br>
    Gender: {{ object.get_gender_display }}<br>
    born_at: {{ object.born_at|date:"d.m Y"}}<br><br>
    Movies:<br><br>
    {% for movie in object.movies.all %}
        {{ movie.name }}<br>
    {% endfor %}
{% endblock body %}

movies/templates/actor_update.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'update_actor' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update actor">
    </form>
    <br><br>
    {% if perms.movies.delete_actor %}
        <a href="{% url 'delete_actor' object.id %}">Delete</a>
    {% endif %}
{% endblock body %}

movies/templates/actors.html
{% include "base.html" %}

{% block body %}
    {% for actor in object_list %}
        <p>{{ actor.name }} age: {{ actor.age }} - <a href="{% url "actor_detail" actor.id %}">detail</a> - <a href="{% url "update_actor" actor.id %}">update</a></p>
    {% endfor %}
{% endblock body %}

movies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background: #fffad3">
<h1>Welcome in hollymovies app - {{ page_name }}</h1><br>

{% block navbar %}
    <a href="{% url 'homepage' %}">Homepage</a><br><br>
    <a href="{% url 'actors' %}">Actors</a><br>
    <a href="{% url 'movies' %}">Movies</a><br>
    <a href="{% url 'directors' %}">Directors</a><br><br>
    <a href="{% url 'create_movie' %}">Create Movie</a><br>
    <a href="{% url 'create_actor' %}">Create Actor</a><br>
    <a href="{% url 'create_director' %}">Create Director</a><br><br>
    <a href="{% url 'jinja2_testing_view' %}">Template cheatsheet</a><br>
    <a href="{% url 'contact_view' %}">Contact</a><br><br>
{% endblock navbar %}

{% block body %}
{% endblock body %}

{% block auth %}
    <br>
    <br>
    <p>User: {{ request.user }}</p>
    <p>Authenticated: {{ request.user.is_authenticated }}</p>
    {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a><br>
        {% if not request.user.profile %}
            <a href="{% url 'create_profile' %}">Create profile</a>
        {% else %}
            <p>{{ request.user.profile.favorite_movie }}</p>
            <p>{{ request.user.profile.address }}</p>
            <p>{{ request.user.profile.language }}</p>
            <a href="{% url 'update_profile' request.user.profile.pk %}">Update Profile</a>
        {% endif %}
    {% else %}
        <a href="{% url 'login' %}">Login</a><br>
        <a href="{% url 'register' %}">SignUp</a>
    {% endif %}
    <br>
    <br>
{% endblock auth %}
</body>
</html>

movies/templates/contact.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'contact_view' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
{% endblock body %}

movies/templates/director_confirm_delete.html
{% extends "base.html" %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete director "{{ object.name }}" from database?
    </p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

movies/templates/director_create.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'create_director' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create director">
    </form>
{% endblock body %}

movies/templates/director_update.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'update_director' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update director">
    </form>
    <br><br>
    <a href="{% url 'delete_director' object.id %}">Delete</a>
{% endblock body %}

movies/templates/directors.html
{% include "base.html" %}

{% block body %}
    {% for director in object_list %}
        <p>{{ director.name }} age: {{ director.age }} - <a href="{% url "director_detail" director.id %}">detail</a> - <a href="{% url "update_director" director.id %}">update</a></p>
    {% endfor %}
{% endblock body %}

movies/templates/homepage.html
{% extends "base.html" %}

{% block navbar %}
    <a href="{% url 'movies' %}">Movies</a><br>
    <a href="{% url 'books' %}">Books</a><br>
{% endblock navbar %}

{% block body %}
    <p>Number of movies - {{ number_of_movies }}</p>
    <p>Number of actors - {{ number_of_actors }}</p>
    <p>Number of directors - {{ number_of_directors }}</p>
    <p>Number of books - {{ number_of_books }}</p>
{% endblock body %}

movies/templates/jinja2_testing.html
{% extends "base.html" %}

{% block navbar %}
    <a href="{% url 'homepage' %}">Homepage</a><br><br>
    <a href="https://www.google.com">google</a><br>
{% endblock navbar %}

{% block body %}
    {{ testing_list.0 }} : {{ testing_list.1 }} : {{ testing_list.2 }}
    <br>
    {{ testing_dict.key_1 }}
    <br>
    {{ testing_queryset.count }}
{% endblock body %}

movies/templates/movie_detail.html
{% include "base.html" %}

{% block body %}
    Name: {{ object.name }}<br>
    Description: {{ object.description }}<br>
    Rating: {{ object.rating }}<br>
    Language: {{ object.get_language_display }}<br>
    Released: {{ object.released|date:"d.m Y"}}<br>
    Likes: {{ object.likes }}<br><br>
    Actors:<br><br>
    {% for actor in object.actors.all %}
        {{ actor.name }}<br>
    {% endfor %}

    <br><br>
    <form action="{% url "movie_detail" object.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Like">
    </form>

{% endblock body %}

movies/templates/movie_update.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'update_movie' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update movie">
    </form>
    <br><br>
    <a href="{% url 'delete_movie' object.pk %}">Delete</a>
{% endblock body %}